### ISSUE TITLE
healthControl, healthServiceType not working

### ISSUE THREAD

**Issue by OwlBawl** [oxystin/homebridge-haier-air-conditioner#6]
"healthControl": true / false => nothing changing, not working 
"healthServiceType": "switch" - not working, cant change device from "bulb" in Homekit, not usefull for Siri control - when switching light on - airconditioner also "on"

**Comment by oxystin** [comment]
> "healthControl": true / false => nothing changing, not working
> "healthServiceType": "switch" - not working, cant change device from "bulb" in Homekit, not usefull for Siri control - when switching light on - airconditioner also "on"

These features are available in version 0.4.0, which is released today. Please update.

**Comment by OwlBawl** [comment]
Just updated - health "false" setting works now, thank you!
